security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        App\Entity\User: auto
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        user:
            entity:
                class: App\Entity\User
                property: username

        my_provider_in_memory:
            memory:
                users:
                    axel:
                        # Ci-dessous le mot de passe "doe" encodé en bcrypt depuis la console :
                       password: password
                       roles: [ROLE_ADMIN]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: user
            pattern: ^/

            form_login:
                check_path: app_login_check
                login_path: app_login
            logout:
                path: app_logout
                target: home
            anonymous: lazy

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

          # activate different ways to authenticate
          # https://symfony.com/doc/current/security.html#firewalls-authentication

          # https://symfony.com/doc/current/security/impersonating_user.html
        # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/blog, roles: ROLE_USER }